name: Build LTL from C++ Source Code

on:
    push:
        tags:
            - 'r*'
        paths:
            - 'csrc/test/**'

permissions:
  contents: write

jobs:
  build_cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install antlr4 tools
        run: |
          pip install --upgrade pip && pip install antlr4-tools

      - name: Generate parser
        run: |
          antlr4 -visitor -no-listener -Dlanguage=Cpp csrc/antlr/LTL.g4

      - name: Build binary from source
        run: xmake -y && sudo xmake install LTL

      - name: Run unit tests
        run: python csrc/test/run.py

      - name: Create GitHub Release and Upload Binary
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/x86_64/release/LTL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
