name: Code Check

on: [push]

jobs:
  pre-check:
    name: Pre-check on Ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
